#!/usr/bin/env bash

create_application_config() {
  touch /root/vof/config/application.yml
  cat <<EOT > /root/vof/config/application.yml
POSTGRES_TEST_DB: "vof_test_db_$1"
GOOGLE_STORAGE_ACCESS_KEY_ID: '$GOOGLE_STORAGE_ACCESS_KEY_ID'
GOOGLE_STORAGE_SECRET_ACCESS_KEY: '$GOOGLE_STORAGE_SECRET_ACCESS_KEY'
USER_MICROSERVICE_API_URL: '$USER_MICROSERVICE_API_URL'
USER_MICROSERVICE_API_TOKEN: "$USER_MICROSERVICE_API_TOKEN"
MAILGUN_DOMAIN_NAME: "$MAILGUN_DOMAIN_NAME"
MAILGUN_API_KEY: "$MAILGUN_API_KEY"
SECRET_KEY_BASE: "$SECRET_KEY_BASE"
EOT
  if [ "$CIRCLE_BRANCH" == master ]; then
    cat <<EOT >> /root/vof/config/application.yml
LOGIN_URL: '$PRODUCTION_LOGIN_URL'
LOGOUT_URL: '$PRODUCTION_LOGOUT_URL'
AUTH_URL: '$PRODUCTION_AUTH_URL'
AUTH_ACCESS_TOKEN: '$PRODUCTION_AUTH_ACCESS_TOKEN'
API_URL: '$PRODUCTION_API_URL'
ANDELA_MICRO_PUBLIC_KEY: "$PRODUCTION_ANDELA_MICRO_PUBLIC_KEY"
LEARNER_MICRO_PUBLIC_KEY: "$PRODUCTION_LEARNER_MICRO_PUBLIC_KEY"
BUGSNAG_KEY: '$PRODUCTION_BUGSNAG_KEY'
ACTION_CABLE_URL: '$PRODUCTION_CABLE_URL'
EOT
  else
    cat <<EOT >> /root/vof/config/application.yml
LOGIN_URL: '$STAGING_LOGIN_URL'
ANDELA_MICRO_PUBLIC_KEY: "$STAGING_ANDELA_MICRO_PUBLIC_KEY"
LEARNER_MICRO_PUBLIC_KEY: "$STAGING_LEARNER_MICRO_PUBLIC_KEY"
LOGOUT_URL: '$STAGING_LOGOUT_URL'
AUTH_URL: '$STAGING_AUTH_URL'
AUTH_ACCESS_TOKEN: '$STAGING_AUTH_ACCESS_TOKEN'
API_URL: '$STAGING_API_URL'
BUGSNAG_KEY: '$STAGING_BUGSNAG_KEY'
ACTION_CABLE_URL: '$STAGING_ACTION_CABLE'
AUTH_URL: '$STAGING_AUTH_URL'
EOT
  fi
}

create_application_config "$@"
